---
- name: Install specific MySQL version
  hosts: vm
  become: yes

  tasks:
    - name: Install MySQL version 8.0.44
      apt:
        name: "mysql-server=8.0.44-0ubuntu0.24.04.1"
        state: present

    - name: Show MySQL version
      command: mysql --version
      register: mysql_version

    - debug:
        var: mysql_version.stdout
