---
- name: Uninstall MySQL Completely
  hosts: vm
  become: yes

  tasks:
    - name: Stop MySQL service
      service:
        name: mysql
        state: stopped
      ignore_errors: yes

    - name: Remove MySQL packages and configs
      apt:
        name: 
          - mysql-server
          - mysql-client
          - mysql-common
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove MySQL data directory
      file:
        path: /var/lib/mysql
        state: absent
