---
- name: Simple Ansible Demo
  hosts: vm
  become: yes   # optional: makes all tasks use sudo

  tasks:

    - name: Create demo directory
      file:
        path: /home/netadmin/demo_folder
        state: directory

    - name: Install MYSQL
      apt:
        name: mysql-server=8.0.45-0ubuntu0.24.04.1
        state: present

    - name: Start Mysql
      service:
        name: mysql
        state: started
        enabled: yes
